stacke:  node.o stack.o test2.o
	g++ -Wall -std=c++11 -g -o stacke node.o stack.o test2.o 

stack: stack.cpp
	g++ -Wall -std=c++11 -g -c node.cpp
	g++ -Wall -std=c++11 -g -c stack.cpp
	g++ -Wall -std=c++11 -g -c test2.cpp
 	

clean:
	rm *.o stacke
	
	
	
	