


labtest: unit_test.o lab.o
	g++ -Wall -std=c++11 -g -o labtest lab.o unit_test.o

lab: lab.cpp
	g++ -Wall -std=c++11 -g -c lab.cpp

unittest: unit_test.cpp
	g++ -Wall -std=c++11 -g -c unit_test.cpp	

clean:
	rm *.o *test
