


labtest:  main.o List.o
	g++ -Wall -std=c++11 -g -o labtest main.o List.o

lab: main.cpp
	g++ -Wall -std=c++11 -g -c main.cpp

unittest: List.cpp
	g++ -Wall -std=c++11 -g -c List.cpp	

clean:
	rm *.o *test