


labtest:  main.o classes.o
	g++ -Wall -std=c++11 -g -o labtest main.o classes.o

lab: main.cpp
	g++ -Wall -std=c++11 -g -c main.cpp

unittest: classes.cpp
	g++ -Wall -std=c++11 -g -c classes.cpp	

clean:
	rm *.o *test