labtest:  main.o
	g++ -Wall -std=c++11 -g -o labtest main.o

lab: main.cpp main.cpp node.h queue.h stack.h Tournament.h
	g++ -Wall -std=c++11 -g -c main.cpp node.h queue.h stack.h Tournament.h


clean:
	rm *.o *test