


labtest: lab_12_unit_test.o lab_12.o
	g++ -Wall -g -o labtest lab.o unit_test.o

lab: lab_12.cpp
	g++ -Wall -g -c lab_12.cpp

unittest: lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp	

clean:
	rm *.o *test
